name: Astro Studio

env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}

on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - db/**

jobs:
  DB:
    name: Sync
    permissions:
      contents: read
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Sync Astro Studio
        uses: withastro/action-studio@main
